server:
  port: 18888

#logging:
#  file: ./logs/springboot.log
#  pattern:
#    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
#    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
#  level:
#    root: info
#    YaJian: debug

spring:
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 80MB
      enabled: true

database:
  directory: ./data

app:
  upload:
    folder: ./uploads
