
server:
  port: 18888

logging:
  file: target/springboot.log
  level:
    root: info
    YaJian: debug

# Do not need below
spring:
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html

database:
  directory: ./data
  save:
    interval: 60000